sulu/sulu-standard

- CHANGELOG.md
- app/Resources/pages/example.xml.dist
__Tasks:__
| Fixed tickets | fixes sulu-cmf/sulu#699
> add single internal link and checkbox to example dist xml

- .travis.yml
- app/AbstractKernel.php
- behat.yml
- composer.json
- composer.lock
- tests/beforetests.sh
- tests/runtests.sh
- tests/sauce/connect_block.sh
- tests/travis-ci-apache
Boostraps behat and does a simple assertion
> Behat integration

- CHANGELOG.md
- src/Client/Bundle/WebsiteBundle/DependencyInjection/ClientWebsiteExtension.php
- src/Client/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
- src/Client/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Client/Bundle/WebsiteBundle/Twig/ClientTwigExtension.php
__Tasks:__
| Fixed tickets | fixes sulu-cmf/sulu#722
> fixes #722 add dependency injection to client website bundle

- app/AbstractKernel.php
- app/config/config.yml
- composer.json
- composer.lock
- web/website.php
See https://github.com/sulu-cmf/sulu/pull/653
and https://github.com/sulu-cmf/sulu-docs/pull/8
> HTTP Cache Integration

- app/config/config.yml
__Tasks:__
| Fixed tickets | fixes #393
> fix cssrewrite

- UPGRADE.md
- app/AbstractKernel.php
- app/config/admin/config.yml
- app/config/admin/routing.yml
- app/config/config.yml
- app/config/parameters.yml.dist
- composer.lock
Main pr https://github.com/sulu-cmf/sulu/pull/684
> Include Websocket Component

- CHANGELOG.md
- composer.json
- composer.lock
This PR adds PHPCR-Shell to Sulu standard as a dev requirement.
It will enable you to connect directly to the configured PHPCR repository as follows
````bash
$ ./app/console doctrine:phpcr:shell
````
And execute arbitrary commands
````bash
$ ./app/console doctrine:phpcr:shell "node:list -L2 /"                                                                           ✭ ◼ │···························································
/ [nt:unstructured] > nt:base                                                                                                                                                      │···························································
+---------------------+-----------------+-----------------+ …
```
> Include phpcr-shell in dev

- app/config/admin/config.yml
- app/config/config.yml
Currently the website is failing, because the SuluAdminBundle is not registered.
> moved sulu_admin configuration to admin configuration

- CHANGELOG.md
- app/Resources/pages/example.xml.dist
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
__Tasks:__
| Tests pass?   | yes
> Added example for present as

- app/config/config.yml
- composer.lock
Applies the changes from https://github.com/sulu-cmf/sulu/pull/878, make a composer update after this merge to see the tests running.
__tasks:__
| q             | a
| tests pass?   | yes
| fixed tickets | none
| bc breaks     | Interface names changes, see UPGRADE.md
| doc           | none
> extracted functionality from security bundle to security component

- CHANGELOG.md
- app/maintenance.php.dist
- web/admin.php
- web/website.php
documentation: https://github.com/sulu-cmf/sulu-docs/pull/16
> [FEATURE] added maintenance mode to admin and website

- CHANGELOG.md
- app/Resources/pages/default.xml.dist
- app/Resources/pages/example.xml.dist
__Tasks:__
| Fixed tickets | fixes #411, fixes #186, fixes #203
| Doc           | https://github.com/sulu-cmf/sulu-docs/pull/23
> Texteditor update example files with new options

- CHANGELOG.md
- UPGRADE.md
- app/AbstractKernel.php
- app/config/admin/config_dev.yml
- app/config/website/config_dev.yml
- composer.json
- composer.lock
__tasks:__
| BC breaks        | Ladybug commands are not available anymore
| Documentation PR |
> removed ladybug

- CHANGELOG.md
- app/config/config.yml
- app/config/parameters.yml.dist
> Delete media response header and ghostscript from default config parameters.yml

- app/config/admin/routing.yml
Should be merged with https://github.com/sulu-io/sulu/pull/999
> removed routing file from snippets being removed

- app/Resources/webspaces/sulu.io.xml.dist
- app/config/website/routing_dev.yml
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/views/error.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/views/error404.html.twig
MAIN PR https://github.com/sulu-io/sulu/pull/1030#
> Fixed variable name for exception controller

- app/AbstractKernel.php
- app/SymfonyRequirements.php
- app/config/config.yml
- app/config/phpcr.yml.dist
- composer.json
- composer.lock
This PR updates Sulu to Jackalope 1.2 and introduces the DoctrineCacheBundle.
The two changes cause a 33% speed increase (more or less).
> Updated to Jackalope 1.2

- app/Resources/pages/default.xml.dist
- app/Resources/pages/example.xml.dist
Related to https://github.com/sulu-io/sulu/pull/1044
> Text editor update

- src/Client/Bundle/WebsiteBundle/Resources/themes/default/blocks/meta.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/default.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/overview.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/overview.rss.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/sitemap.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/views/master.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/views/navigation.html.twig
MAIN PR: https://github.com/sulu-io/sulu/pull/1234
> Prefix twig extension functions with "sulu_"

- app/AbstractKernel.php
- app/SymfonyRequirements.php
- app/config/admin/config.yml
- app/config/config.yml
- composer.json
- composer.lock
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/default.html.twig
Also adds thre PHPCR integrations.
> Feature/refactoring integration into Sulu Standard

- app/AbstractKernel.php
- composer.json
- composer.lock
Enabled `PersistenceBundle`
__Tasks:__
| Tests pass?   | no => https://github.com/sulu-io/sulu/pull/1230 
> Persistence Bundle

- app/Resources/webspaces/sulu.io.xml.dist
- app/config/config.yml
- composer.json
- composer.lock
MAIN PR: https://github.com/sulu-io/sulu/pull/1281
> Added default-template to webspace theme

- CHANGELOG.md
- app/AdminKernel.php
__Tasks:__
__Information:__
| Q                | A
> Register SuluGeneratorBundle

- CHANGELOG.md
- composer.lock
- tests/beforetests.sh
Has to be merged with https://github.com/sulu-io/sulu/pull/1366
The sulu:build command is used to setup the test database, because there was an error not covered by the tests.
> Use sulu:build for test setup

- app/config/sulu.yml
See main pr https://github.com/sulu-io/sulu/pull/1448
> Fixed additional system languages

- .styleci.yml
- app/AbstractKernel.php
- app/Resources/pages/example.xml.dist
- src/Client/Bundle/WebsiteBundle/DependencyInjection/ClientWebsiteExtension.php
- src/Client/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
- web/website.php
Main PR https://github.com/sulu-io/sulu/pull/1415
> Added dataprovider examples

- CHANGELOG.md
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/blocks/meta.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/complex.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/default.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/overview.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/sitemap.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/views/master.html.twig
Applies changes from https://github.com/sulu-io/sulu/pull/1539
> use sulu_seo twig method instead of deprecated sulu_meta_seo

- composer.lock
- src/Client/Bundle/WebsiteBundle/Controller/SearchController.php
Merge with: https://github.com/sulu-io/sulu/pull/1617
__tasks:__
> changed website search to also match parts of words

- app/Resources/pages/example.xml.dist
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
Main PR: https://github.com/sulu-io/sulu/pull/1347
> Added example for contact selection

- CHANGELOG.md
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/overview.html.twig
Main PR: https://github.com/sulu-io/sulu/pull/1538
> Added tags list to overview twig template

- CHANGELOG.md
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/overview.html.twig
Error in rendering because variable app not exists in preview mode.
__tasks:__
> Fixed default template preview

- CHANGELOG.md
- app/Resources/pages/example.xml.dist
- composer.lock
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
__tasks:__
| Fixed tickets    | fixes https://github.com/sulu-io/sulu/issues/1727
> Fixed usage of block property

- CHANGELOG.md
- app/config/admin/sulu.yml
- composer.lock
Main PR: https://github.com/sulu-io/sulu/pull/1739
> Added system-collection build task

- CHANGELOG.md
- app/config/sulu.yml
- src/Client/Bundle/WebsiteBundle/Controller/SearchController.php
Should be merged with https://github.com/massiveart/MassiveSearchBundle/pull/68
> updated configuration due to changes in MassiveSearchBundle

- CHANGELOG.md
- UPGRADE.md
- app/Resources/pages/example.xml.dist
- composer.lock
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
__tasks:__
| Related PRs      | none
> updated example template

- app/Resources/pages/example.xml.dist
- composer.lock
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
__tasks:__
| Related PRs      | https://github.com/sulu-io/sulu/pull/1777
> added selection content type to example template

- CHANGELOG.md
- app/AbstractKernel.php
__tasks:__
| Related PRs      | https://github.com/sulu-io/sulu/pull/1956
> added translation bundle

- app/AbstractKernel.php
- app/AdminKernel.php
- app/WebsiteCache.php
- app/WebsiteKernel.php
- app/config/router_admin.php
- app/config/router_website.php
- app/config/sulu.yml
- src/Client/Bundle/WebsiteBundle/ClientWebsiteBundle.php
- src/Client/Bundle/WebsiteBundle/Controller/SearchController.php
- src/Client/Bundle/WebsiteBundle/DependencyInjection/ClientWebsiteExtension.php
- src/Client/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
- src/Client/Bundle/WebsiteBundle/Twig/ClientTwigExtension.php
- tests/bootstrap.php
- web/admin.php
- web/website.php
| Related PRs      | https://github.com/sulu-io/sulu/pull/1970
> removed jms serializer parameter configuration

- app/config/sulu.yml
| Related PRs      | https://github.com/sulu-io/sulu/pull/1986
> use correct serialization naming strategy

- CHANGELOG.md
- app/config/sulu.yml
- composer.json
- composer.lock
Main PR: https://github.com/sulu-io/sulu/pull/2000
> Added oro doctrine extension for group-concat and other functions

- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/overview.rss.twig
Main PR: https://github.com/sulu-io/sulu/pull/2182
> Changed resolve user function

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
| Q | A
| --- | ---
| Fixed tickets | 
| Related issues/PRs | #635
This PR copies in the GitHub issue/PR templates from sulu-io/sulu.
This update was forgotten in #635.
> Included issue/PR templates from sulu-io/sulu

- app/Resources/webspaces/sulu.io.xml.dist
- composer.lock
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu-io/sulu/pull/2175
> Fixed dist file to match new validation of locales

- tests/runtests.sh
| Q | A
| --- | ---
Removes the dependecy on sulu-io/sulu test runner.
We refactored the test runner and removed a file that this repository dependended on, it was a non-essential file (just showed the Sulu logo in ASCII), so I just removed the reference to it.
> Fixed tests (removed dep. on sulu-io/sulu build script)

- CHANGELOG.md
- UPGRADE.md
- composer.lock
- web/.htaccess
__Tasks:__
| Fixed tickets | fixes #574 
| BC Breaks     | yes
| Doc           | https://github.com/sulu-io/sulu-docs/pull/193
> Remove default htaccess environment

- src/Client/Bundle/WebsiteBundle/Resources/config/routing.yml
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/views/master.html.twig
Updates `ClientWebsiteBundle` to fit new custom-routes name. See sulu-pr https://github.com/sulu-io/sulu/pull/2204
> Enhanced custom-route creation

- app/Resources/webspaces/sulu.io.xml.dist
- composer.lock
This PR changes the default webspace and the route-generation to fit this sulu-pr https://github.com/sulu-io/sulu/pull/2203/files
> Adaptions for wildcard URLs

- CHANGELOG.md
- app/Resources/webspaces/sulu.io.xml.dist
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/default.html.twig
- src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig
| Q | A
| --- | ---
This PR removes the custom-url from the webspace dist.
> Removed custom-urls from webspace dist files

- CHANGELOG.md
- app/config/admin/config_stage.yml
- app/config/admin/sulu.yml
- app/config/config.yml
- app/config/sulu.yml
- app/config/website/config_stage.yml
| Q | A
| --- | ---
This PR removes the deprecations introduces by the Symfony YAML component to be compatible with the YAML specification.
In some environment the tests were failing because of that.
> Fixed new yaml deprecations

- app/AbstractKernel.php
- app/AdminKernel.php
- composer.lock
This PR includes the new sulu-bundles preview and route. The main PR can be found here https://github.com/sulu/sulu/pull/2299
> Added preview and route-bundle

- UPGRADE.md
- app/AbstractKernel.php
- app/AdminKernel.php
- app/WebsiteCache.php
- app/WebsiteKernel.php
- app/config/admin/config.yml
- app/config/admin/routing.yml
- app/config/website/routing.yml
- composer.json
- composer.lock
- web/admin.php
- web/website.php
This PR fixes the classmap in sulu to be able to autoload the kernel-files. Will be needed in PR https://github.com/sulu/sulu/pull/2357 .
After merging this every installation has to run composer update to regenerate the autoloader.
> Fixed composer classmap and added kernel names

- app/AbstractKernel.php
- app/Resources/webspaces/sulu.io.xml.dist
- composer.json
- composer.lock
This PR introduces the sulu/theme-bundle. This is necessary to keep BC after https://github.com/sulu/sulu/pull/2408
> Added sulu theme-bundle to keep backward compatability

- app/AbstractKernel.php
- app/AdminKernel.php
- app/config/admin/sulu.yml
- app/config/sulu.yml
- app/config/website/sulu.yml
This PR makes needed changes to work with https://github.com/sulu/sulu/pull/2464
> Moved configuration to sulu-core

- app/Resources/webspaces/sulu.io.xml.dist
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2665
This PR corresponds to the change in https://github.com/sulu/sulu/pull/2665.
Due to the latest changes the standard configuration here does not work anymore.
> adapted webspace xml dist file

- app/Resources/pages/example.xml.dist
| Q | A
| --- | ---
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| Documentation PR | sulu-io/sulu-docs#prnum
see title
> Fixed typos in lang attributes of 'example.xml.dist'

- app/Resources/webspaces/sulu.io.xml.dist
Needed change to fit new xml schema introduced by https://github.com/sulu/sulu/pull/2729
> Removed resource-locator strategy from webspace config

- UPGRADE.md
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2808
Add missing upgrade.md from 1.3.0-RC1.
> add removed image format to upgrade

- CHANGELOG.md
- app/config/sulu.yml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3015
See https://github.com/sulu/sulu/pull/3015
> Deactivate public in dev/stage environment

- README.md
| Q | A
| --- | ---
| Fixed tickets | -
| Related issues/PRs | -
The Readme contained a wrong link to the getting started guide. This PR corrects it.
> Correct path to getting started guide

- app/AbstractKernel.php
- app/config/admin/routing.yml
- composer.json
Main PR https://github.com/sulu/sulu/pull/3037
> Added automation-bundle

- CHANGELOG.md
- app/AdminKernel.php
- composer.json
Main PR https://github.com/sulu/sulu/pull/3084
> Removed generator-bundle

- .travis.yml
- app/AbstractKernel.php
- app/config/sulu.yml
- composer.json
Main PR https://github.com/sulu/sulu/pull/3068
> Removed phpcr-odm

- CHANGELOG.md
- app/config/admin/security.yml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu-minimal/pull/34
This PR removes the ACL configuration.
The ACL tables from Symfony were generated, although we do not use them.
> removed acl configuration

- CHANGELOG.md
- app/config/website/sulu.yml
Main PR https://github.com/sulu/sulu/pull/3110
> Removed exception-controller from config

- .gitignore
- composer.json
Integration of https://github.com/sulu/sulu/pull/3142
> added script handler to delete the composer.lock file from gitignore

- README.md
| Q | A
| --- | ---
| Fixed tickets | ---
| Related issues/PRs | ---
| Documentation PR | ---
This PR adds a link to [Browserstack](https://www.browserstack.com/) which is required to get the open source licence.
> added browserstack link to readme

- CHANGELOG.md
- app/config/admin/security.yml
- app/config/sulu.yml
- composer.json
- tests/runtests.sh
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3154
This PR updates this distribution to symfony 3.
> Updated dependencies and fixed symfony3 deprecations

- composer.json
Main PR https://github.com/sulu/sulu/pull/3278
> Removed sulu version

- app/config/admin/routing.yml
This PR includes the newly introduced `routing_api.xml` file of the route-bundle (see https://github.com/sulu/sulu/pull/3315).
> Added route-api file

- composer.json
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/362
This PR add ffmpeg-bundle to composer.json
> Added ffmpeg-bundle to composer.json

- README.md
| Q | A
| --- | ---
| Fixed tickets | fixes #855
Update readme file for sulu minimal
That somebody starts new project with sulu-standard edition
> Update readme file for sulu minimal
