sulu/sulu-standard

web/.htaccess
web/admin.php
web/website.php

I think we should use SYMFONY_ENV variable for checking the SF environment, since Symfony already works with it. If you check `console` file, we can see, that there it uses this one and not APP_ENV. For BC I left APP_ENV to be checked first, if this one is not present, try with SYMFONY_ENV.
|       Q         |                        A                         |
| -------------- |:------------------------------------------------|
| Tests pass? | none |
| Fixed tickets  | none                                     |
| BC Breaks    | none                              |
| Doc    | none                              |

App should also take SYMFONY_ENV variable, to check for SF environment.

---

composer.json
composer.lock

Jackelope-doctrine-dbal moved from require-dev to require. Although, during the composer update, some guzzle paths were also changed so please check that.
__tasks:__
| q             | a
| Bug fix?      | no
| Tests pass?   | yes

Jackelope-doctrine-dbal moved from require-dev to require

---

CHANGELOG.md
app/config/sulu.yml

__tasks:__
| Related PRs      | https://github.com/sulu-io/sulu/pull/1846
| BC breaks        | `sulu_core.content.structure.typeMap` is now `sulu_core.content.structure.type_map`

fixed name of type map config parameter

---

CHANGELOG.md
app/config/config.yml

actually use the fix @dantleech made in https://github.com/liip/LiipThemeBundle/pull/118
| Related PRs      | none

enabled assetic integration of LiipThemeBundle

---

composer.lock

When installing the current Sulu Standard Edition, an exception is thrown when running `composer install`:
> Fatal error: Class 'Sulu\Bundle\HashBundle\SuluHashBundle' not found
This bundle was added in https://github.com/sulu-io/sulu-standard/commit/4d3239fc755e9c46c020cdd4403337d96615cf1a without updating the composer.lock file. I did this now.

Updated sulu/sulu dependency since currently the SuluHashBundle is missing

---

CHANGELOG.md
composer.json
composer.lock

| Q | A
| --- | ---
| Tests pass? | w00t
| Related PRs | sulu-io/sulu#2082
With the new `react/socket` release 0.4.3 which requires again `evenement/evenemt: ^2.0|^1.0` it's possible to get rid of the aliased statement.
Such an easy pick the new react release, after I begun to clean up the libs which require the v1.0 :weary:

[WIP] [SULU-STANDARD] Get rid of the aliased evenement composer constraint

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR copies over the PR and issue templates from the [sulu-io/sulu](/sulu-io/sulu) repository.

Added PR and issue templates for GitHub

---

app/config/admin/sulu.yml
app/config/website/sulu.yml
composer.lock

| Q | A
| --- | ---
| Fixed tickets | fixes #640
Disables the REST exception listener for the website.
Because the error pages didn't work anymore.

Disable REST exception listener for the website

---

CHANGELOG.md
composer.json
composer.lock

| Q | A
| --- | ---
| New feature? | yes
| Documentation PR | https://github.com/sulu/sulu-docs/pull/200
This PR makes use of the changes in https://github.com/massiveart/MassiveSearchBundle/pull/80, so that the user doesn't have to create the search directory directly. (also see change in https://github.com/sulu/sulu-docs/pull/200)
Because creating the directory automatically makes the installation process easier and less error-prone. This change also means that the user can change the directory for the search in the configuration, and the installation instructions would still work (only the permissions have to be corrected, maybe we should also use a command for …

Use composer handler to create search directory

---

CHANGELOG.md
app/config/admin/security.yml
composer.json
composer.lock

| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2324
This PR uses the newly introduced `UserProvider`, which splits the required functionality for the Symfony security system from the Doctrine Repository.
Because this way is cleaner, and resolves a circular referencing issue we had, when using the security on the website.

Use the new UserProvider for the security

---

CHANGELOG.md
app/maintenance.php.dist

| Q | A
| --- | ---
| Fixed tickets | 
| Related issues/PRs |  
| Documentation PR | 
It sets the 503 status code in the maintenance template.
A maintenance page should be from status code 503.

Add 503 status code to maintenance template

---

app/AbstractKernel.php
app/WebsiteKernel.php

This PR moves the markup-bundle to the abstract-kernel. This will be needed in https://github.com/sulu/sulu/pull/2402

Moved markup-bundle to abstract-kernel

---

CHANGELOG.md
UPGRADE.md
composer.lock
src/Client/Bundle/WebsiteBundle/Resources/themes/default/views/master.html.twig

| Q | A
| --- | ---
| PR | sulu/sulu#2484
Add `request.routeParameters` (host, prefix) automatically for route generator.
When you render your own template and have no `request.routeParameters` you needed to call the request analyzer or create a twig extension which will load from the current request routeParameters.
```twig
{{ path('client_website.search') }}
{{ url('client_website.search') }}
```

Add host and prefix automatically for route generator

---

UPGRADE.md

| Q | A
| --- | ---
| Fixed tickets | 
| Related issues/PRs | 
| Documentation PR | 
Removed the "Composer autoloader" section from the upgrade instructions for 1.3.0-RC1.
Not needed as composer update or install is executed anyway during an update. Was already removed in sulu/sulu.

Removed composer update (was already removed in sulu/sulu)

---

CHANGELOG.md
app/config/sulu.yml

| Q | A
| --- | ---
| Fixed tickets | -
| Related issues/PRs | https://github.com/sulu/sulu/pull/2648
This PR removes the HTTP Cache PathsHandler configuration from the sulu.yml file.
The HTTP Cache integration got refactored and the PathsHandler got removed.
(https://github.com/sulu/sulu/pull/2648)

removed http cache paths-handler from configuration

---

CHANGELOG.md
composer.json
composer.lock
src/Client/Bundle/WebsiteBundle/Resources/themes/default/config/image-formats.xml

| Q | A
| --- | ---
| Fixed tickets | -
| Related issues/PRs | https://github.com/sulu/sulu/pull/2845
The image-formats configuration file of the website-bundle was adapted to meet the requirements of the new version for defining image-formats.
The PR https://github.com/sulu/sulu/pull/2845 introduced a new version for defining image-formats. As sulu-standard want's to provide a current, up-to-date example on how a simple project using sulu looks like, the configuration files had to updated.

Refactored the image-formats of the default theme to meet new image-formats version

---

CHANGELOG.md
app/Resources/pages/default.xml.dist
composer.lock
src/Client/Bundle/WebsiteBundle/Resources/themes/default/config/image-formats.xml
src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/default.html.twig

| Q | A
| --- | ---
| Fixed tickets | -
| Related issues/PRs | -
The new method of defining image-formats allows for defining readable translations for an image format. This PR adds titles to the image-formats in sulu-standard.

Added title to header image format and made use of 640x480 format

---

CHANGELOG.md
src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/default.html.twig

| Q | A
| --- | ---
| Fixed tickets | fixes #740
This PR changes the way the categories are accessed in the twig template.

fixed category access in default twig template

---

app/config/admin/sulu.yml
app/config/sulu.yml
app/config/website/sulu.yml

| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3014
This PR removes the context specific configurations. The session can theoretically still be changed, but practically it is still not possible to do because of https://github.com/phpcr/phpcr-migrations/issues/4
Because with sulu/sulu#3014 they are not necessary anymore.

removed sessions from context specific configurations

---

CHANGELOG.md
src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig

| Q | A
| --- | ---
| Documentation PR | sulu-io/sulu-docs#prnum
Modified check in `example.html.twig?` for view elements. Now the check returns `true` if elements available since the previous check alltimes returns `true`.
Because the previous check makes no sense. The old check returns alltimes `true`.

Update example.html.twig with better check if view has elements

---

composer.json
src/Client/Bundle/WebsiteBundle/Resources/themes/default/config/image-formats.xml

| Q | A
| --- | ---
| Fixed tickets | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3040
| Documentation PR | ---
This PR adds an image format which was used in a template in this project.
It was working previously because the image format existed in sulu/sulu, but it was removed there.

added image format which was not defined

---

app/AbstractKernel.php
app/config/admin/routing.yml
composer.json

| Q | A
| --- | ---
| Fixed tickets | fixes #3181
| Related issues/PRs | https://github.com/sulu/sulu/issues/3181
| Documentation PR | ---
This PR adapts to the changes which were made, because the `SuluAutomationBundle` has been extracted from the standard.

removed automation-bundle from default installation

---

CHANGELOG.md
app/config/config.yml
composer.json

| Q | A
| --- | ---
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| Documentation PR | sulu-io/sulu-docs#prnum
Added ClientWebsiteBundle to Assetic configuration and sulu/document-manager to composer.json.
`composer install` on branch develop did not work (missing dependecy sulu/document-manager).
`app/console assetic:dump` did not include the ClientWebsiteBundle, which is delivered along the sulu/sulu-standard repository.
- Fixed Assetic dump to include the sulu-standard bundle 'ClientWebsiteBundle'.
- Fixed the composer.json file to include the sulu/document-manger as a dependency.

Bugfix/Added ClientWebsiteBundle to Assetic configuration and sulu/document-manager to composer.json

---

.travis.yml
CHANGELOG.md
web/admin.php
web/website.php

| Q | A
| --- | ---
Remove deprecated apcu example in admin.php and website.php.
It can end in strange errors when use the new recommended way over composer `composer install --apcu-autoloader`.
~~~bash
composer install --apcu-autoloader
~~~

Remove deprecated apcu example in website.php and admin.php

---

app/Resources/webspaces/sulu.io.xml.dist

| Q | A
| --- | ---
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
Rename startpage type from homepage to new home.
It throws an error in the webspace validate command as the type is not found.
```bash
app/console sulu:content:validate:webspaces
```

Fix home type in example webspace

---

.travis.yml
CHANGELOG.md
app/AbstractKernel.php
composer.json
tests/beforetests.sh

| Q | A
| --- | ---
Allow symfony 2.8 and check if web server bundle exists.
Fix the compatibility with php 5.5 
~~~php
php55 /usr/local/bin/composer install
~~~

Fix compatibility with php 5.5

---

CHANGELOG.md
app/config/admin/config_test.yml
app/config/website/config_test.yml

| Q | A
| --- | ---
| Realted PRs? | https://github.com/sulu/sulu-minimal/pull/109
Set the massive_search_prefix to `test` in test environment.
Currently the test write into the same index as the other environment which should be avoided.
~~~php
SYMFONY_ENV=test bin/simple-phpunit
~~~

Fixes that test environment write into same index as live
